CREATE TABLE alerts (
	id VARCHAR(3) NOT NULL,
	callback VARCHAR(10) NOT NULL,
	url VARCHAR(255) NOT NULL,
	hash VARCHAR(128),
	PRIMARY KEY (url),
	UNIQUE KEY (id)
);

CREATE TABLE sms (
	id INTEGER NOT NULL AUTO_INCREMENT,
	`from` VARCHAR(10) NOT NULL,
	`to` VARCHAR(10) NOT NULL,
	message TEXT NOT NULL,
	PRIMARY KEY (id)
);
